### ISSUE TITLE
database locked if xxdiff is open

### ISSUE THREAD

**Issue by arjclark** [metomi/fcm#179]
If a user has xxdiff open when they try to commit their code they get a message about the database being locked.

It has been requested that something a bit more friendly could be printed e.g.

```
ERROR: cannot commit database is locked ...
 - check [xxdiff] is not open and try again
```

**Comment by dpmatthews** [comment]
The message produced by Subversion is as follows:
```
svn: E200033: Another process is blocking the working copy database, or the underlying filesystem does not support file locking; if the working copy is on a network filesystem, make sure file locking has been enabled on the file server
svn: E200033: Commit failed (details follow):
svn: E200033: sqlite[S5]: database is locked
svn: E200033: Additional errors:
svn: E200033: sqlite[S5]: database is locked
```
Since the message comes from Subversion this is not really an FCM issue.

This only happens because we have configured Subversion to use exclusive SQLite locking to improve working copy performance (see http://subversion.apache.org/docs/release-notes/1.8.html#exclusivelocking).

Users who don't like this (and are prepared to live with slower working copy performance) can disable it by adding the following to their `.subversion/config` file:
```ini
[working-copy]
exclusive-locking-clients =
```

Most (not sure if it's all) of the problems we get with this are when a user is running `fcm diff --graphical`.  We could avoid this by using the option `--config-option config:working-copy:exclusive-locking-clients=` with this command. The diff command would be slower but most users probably wouldn't notice. Perhaps we should add a special configuration option for this and make it our site default?

**Comment by matthewrmshin** [comment]
I'll close this issue down as it is a site configuration issue.

**Comment by dpmatthews** [comment]
I think this is worth doing given the pain it causes. We would need to be able to configure an extra option to be passed to `svn diff` whenever a user is running the `fcm diff --graphical` command.
